all_emails = ["sasha@microminds.ru", "eva@retarded.ru", "veronica@dolt.io", "ivan@retarded.ru"]


def extract_domain(...):
    ...
    return ...


def organize_emails(all_emails):
    ...
    return ...